### ISSUE TITLE
Could not retrieve mirrorlist http://mirrorlist.centos.org/

### ISSUE THREAD

**Issue by dcmspe** [NFarrington/docker-nagios-log-server#1]
Hey dude,

I am trying to use your docker image. Howerver, I am getting the following error when I try to `$ run docker build`:

```
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os&infra=container error was
14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrorlist.centos.org'"
The command '/bin/sh -c yum -y install wget' returned a non-zero code: 1
```

Any ideas about how to fix it?

**Comment by NFarrington** [comment]
Seems like there's an issue with your DNS/networking within the container (and possibly the docker configuration on the host machine). I'd recommend checking your DNS and iptables/other firewall settings on the host machine. https://www.google.co.uk/search?q=docker+centos+%22Couldn%27t+resolve+host+%27mirrorlist.centos.org%27%22

Alternatively, you can try pulling down a pre-built image with `docker pull nfarrington/nagios-log-server`.

**Comment by dcmspe** [comment]
Thanks in advance! :)
